### ISSUE TITLE
[Looked into "Usage with ranger"] How to use rsop in ranger?

### ISSUE THREAD

**Issue by kohane27** [desbma/rsop#2]
Hello there. Hope you're doing well. Thank you for creating `rsop`.

I understand that it may be a stupid question, but please bear with me.

I've looked into the [Usage with ranger](https://github.com/desbma/rsop#usage-with-ranger) but still can't figure out how to use `rsop` in `ranger`.

## What I've tried

1. Remove the original entire content of [rifle.conf](https://github.com/ranger/ranger/blob/master/ranger/config/rifle.conf)  and add the following in `rifle.conf`:

```
ext * = rso "$@"
```

The reason is that, we're using `rsop` to match against all extensions, hence the above syntax.

2. Remove the original content of [scope.sh](https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh) and replace with the following:

```
RSOP_MODE=open COLUMNS="$2" LINES="$3" exec rsop "$1"
```

So the entire content of `scope.sh` becomes the above one line.

3. Open ranger again

4. Navigate to `rc.conf` and ranger has the following error output:

```
Loader work process failed: Getting preview of /home/username/.config/ranger/scope.sh (Percent: 0)
```

![2023-04-21-20-00-38](https://user-images.githubusercontent.com/57322459/233663117-0de32d14-8c5c-4fc3-a2e8-94fdbe6fa1a1.png)

6. When I tried to open the file with `l`, the following output occurs:

```
nothing to repeat at position 2
```
![2023-04-21-20-00-43](https://user-images.githubusercontent.com/57322459/233663161-f8e079a0-e273-4901-ae18-7e8f7be51a42.png)

Any input is much appreciated. Thank you.

**Comment by desbma** [comment]
Hi, thanks for the kind words.

The instructions were incorrect in the README, I have [updated them](https://github.com/desbma/rsop/commit/11e87e3fafa355c91b229b59229e8d7bf42ab683).

For `scope.sh`, you need:
```
#!/bin/sh
RSOP_MODE=preview COLUMNS="$2" LINES="$3" exec rsop "$1"
```

**Comment by kohane27** [comment]
Apologies for my late reply. Just tested and it works perfectly now. Thank you for looking into this issue!
